version: '3.1'
services:
  eureka-server:
    build: ./EurekaServer
    container_name: eureka-server
    ports:
      - 8761:8761

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    ports:
      - "54320:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_MULTIPLE_DATABASES: message_service,user_service
    depends_on:
      - eureka-server

  message-service:
    build: ./MessageService
    container_name: message-service
    ports:
      - 8081:8081
    depends_on:
      - postgres
    links:
      - eureka-server

  auth-service:
    build: ./AuthService
    container_name: auth-service
    ports:
      - 8082:8082
    depends_on:
      - postgres
      - eureka-server

  api-gateway-service:
    build: ./ApiGatewayService
    container_name: api-gateway-service
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
      - message-service
      - auth-service

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test123"
    ports:
      - "16543:80"
    depends_on:
      - api-gateway-service
